### ISSUE TITLE
New filter to exclude a set of methods

### ISSUE THREAD

**Issue by alexanderilyin** [sebastianbergmann/phpdcd#3]
Possible it could use some @docblock or xml file. I'm using Zend Framework and all action methods (for example like myCustomFooBarAction) in controllers are dead, it's not right becouse it's expected that they aren't called directly, I would like to handle this case.

**Comment by sebastianbergmann** [comment]
I lost interest in this project a long time ago, mostly due to the [limitations](https://github.com/sebastianbergmann/phpdcd#limitations) of its implementation. Today I [added](https://github.com/sebastianbergmann/phpdcd/commit/69885271da311d3e849706306ae038f775d1ee99) a note that this project is no longer maintained to its documentation and closed all open tickets. Feel free to continue to work on this in a fork.
