### ISSUE TITLE
"Class name must be a valid object or a string in Token/Stream.php on line 218"

### ISSUE THREAD

**Issue by bskendig** [sebastianbergmann/phpdcd#41]
When I run "phpdcd src" to check my codebase, it prints the version line (phpdcd 1.0.1 by Sebastian Bergmann.) then sits for about a minute before failing with this error:

Fatal error: Class name must be a valid object or a string in phar:///usr/local/bin/phpdcd/php-token-stream/Token/Stream.php on line 218

Using "-vvv" for debugging info doesn't generate any additional output.

**Comment by sebastianbergmann** [comment]
I lost interest in this project a long time ago, mostly due to the [limitations](https://github.com/sebastianbergmann/phpdcd#limitations) of its implementation. Today I [added](https://github.com/sebastianbergmann/phpdcd/commit/69885271da311d3e849706306ae038f775d1ee99) a note that this project is no longer maintained to its documentation and closed all open tickets. Feel free to continue to work on this in a fork.
