### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by seferov** [sebastianbergmann/phpdcd#42]
Why test methods are considered as a dead code? I think it should ignore unit tests.

**Comment by sebastianbergmann** [comment]
I lost interest in this project a long time ago, mostly due to the [limitations](https://github.com/sebastianbergmann/phpdcd#limitations) of its implementation. Today I [added](https://github.com/sebastianbergmann/phpdcd/commit/69885271da311d3e849706306ae038f775d1ee99) a note that this project is no longer maintained to its documentation and closed all open tickets. Feel free to continue to work on this in a fork.
