### ISSUE TITLE
Variable function calls

### ISSUE THREAD

**Issue by edsonmedina** [sebastianbergmann/phpdcd#44]
phpdcd doesn't know when methods are used anonymously because it's obviously impossible to know that via static analysis. 

So take this example:

    function doAction ($action, $data) 
    {
        switch ($action) 
        {
            case "new":
                $method = "insertData";
                break;
            case "save":
                $method = "updateData";
                break;
        }
        call_user_func ($method, $data);
    }

Both `insertData` and `updateData` will be reported as dead code, because there's simply no way to predict all possible values for $method without some sort of list. 

Unless you're human, that is.

What if we could define some matching rules (ie: via regex) that would match the resulting strings as "usages"?

For example:

    $config['anynomousUsagesMatch'] = array (
        'doAction' => '/\$method => \"(.*?)\"/',
    );

This would restrict the matching to be done inside the `doAction` function (because we don't want to match all the code), and those matches would be handled as code usages.

Does this make any sense to you? Sounds too hackish?

Personally, I'd love to have some similar feature. It could be useful handling anonymous function calling that otherwise couldn't be detected.

**Comment by sebastianbergmann** [comment]
I lost interest in this project a long time ago, mostly due to the [limitations](https://github.com/sebastianbergmann/phpdcd#limitations) of its implementation. Today I [added](https://github.com/sebastianbergmann/phpdcd/commit/69885271da311d3e849706306ae038f775d1ee99) a note that this project is no longer maintained to its documentation and closed all open tickets. Feel free to continue to work on this in a fork.
