### ISSUE TITLE
Treat all "...Action()" methods as being called

### ISSUE THREAD

**Issue by bskendig** [sebastianbergmann/phpdcd#46]
When used against a web site codebase such as Zend, where "...Action()" methods are called by routes in a web framework, phpdcd doesn't see these methods as being called so therefore it thinks that most or all of the codebase is dead.

If phpdcd could assume that each action is called (at least) once, that would let it be used with web site code.

Alternately, it could be useful for phpdcd to accept a list (or pattern) representing methods it should assume are called at least once.

**Comment by sebastianbergmann** [comment]
I lost interest in this project a long time ago, mostly due to the [limitations](https://github.com/sebastianbergmann/phpdcd#limitations) of its implementation. Today I [added](https://github.com/sebastianbergmann/phpdcd/commit/69885271da311d3e849706306ae038f775d1ee99) a note that this project is no longer maintained to its documentation and closed all open tickets. Feel free to continue to work on this in a fork.
