### ISSUE TITLE
Polymorphism not handled properly

### ISSUE THREAD

**Issue by andrewboerema** [sebastianbergmann/phpdcd#47]
I'm not sure whether it was intended to be supported, but it appears certain scenarios under polymorphism are not supported. For example if a child class defines a function *handleRequest()*, but only the parent class calls that function, the tool will mark it as dead.

I am considering forking the project to add support for this scenario plus a few others under some kind of "careful" mode. In this "careful" mode, the tool would look for a set of possible usages and report those.

* polymorphism scenario above
* user_funcs
* functions called from behind a variable
* constructed function names

That is probably a much larger effort than fixing this small issue with polymorphism, so I wanted to raise this issue specifically.

**Comment by sebastianbergmann** [comment]
I lost interest in this project a long time ago, mostly due to the [limitations](https://github.com/sebastianbergmann/phpdcd#limitations) of its implementation. Today I [added](https://github.com/sebastianbergmann/phpdcd/commit/69885271da311d3e849706306ae038f775d1ee99) a note that this project is no longer maintained to its documentation and closed all open tickets. Feel free to continue to work on this in a fork.
