### ISSUE TITLE
singleton and phpdcd

### ISSUE THREAD

**Issue by Stephan123** [sebastianbergmann/phpdcd#56]
Hello,

I started to concern myself with phpdcd .
I have a class .
This class is a singleton pattern .

In this class are public methods . By phpdcd these functions are recognized as dead code . But these functions are called . Is there a solution.

With best regards

Stephan

**Comment by sebastianbergmann** [comment]
I lost interest in this project a long time ago, mostly due to the [limitations](https://github.com/sebastianbergmann/phpdcd#limitations) of its implementation. Today I [added](https://github.com/sebastianbergmann/phpdcd/commit/69885271da311d3e849706306ae038f775d1ee99) a note that this project is no longer maintained to its documentation and closed all open tickets. Feel free to continue to work on this in a fork.
